---
- include: logstash_deb.yaml tags=logstash
  when: ansible_distribution in [ 'Debian', 'Ubuntu' ]

- include: logstash_rpm.yaml tags=logstash
  when: ansible_distribution in [ 'Red Hat Enterprise Linux', 'CentOS', 'Amazon' ]

- name: create conf.d
  file: path={{ item }} state=directory owner=root group=root mode=0644
  sudo: yes
  with_items:
    - /etc/logstash
    - /etc/logstash/conf.d

- name: install logstash service defaults
  template: src=etc/sysconfig/logstash.j2 dest=/etc/sysconfig/logstash
  notify:
    - restart logstash service
  
- name: logstash config build
  template: src=config.j2 dest=/etc/logstash/conf.d/{{ item.config_file }}
  sudo: yes
  with_items: logstash_config 
  notify:
    - restart logstash service
