---
- name: "create logstash directories"
  action: file path={{ item }} group=root owner=root mode=0755 state=directory
  with_items:
    - '{{ logstash.dir }}'
    - '{{ logstash.dir }}/bin'
    - '{{ logstash.dir }}/etc'
    - '{{ logstash.dir }}/log'

- name: "fetch logstash"
  get_url: url={{ logstash.url }}/{{ logstash.jar }} dest={{ logstash.dir }}/bin/{{ logstash.jar }} mode=0440
  register: get_jar

- name: install logstash indexer config
  action: template src=etc/logstash/indexer.conf.j2 dest={{ logstash.dir }}/etc/{{ logstash.indexer.conf }} owner=root group=root mode=0644
#  when: with_indexer
  notify:
    - "restart logstash indexer"

- name: "install logstash shipper config"
  action: template src=etc/logstash/shipper.conf.j2 dest={{ logstash.dir }}/etc/{{ logstash.shipper.conf }} owner=root group=root mode=0644
#  when: with_shipper
  register: logstash_shipper_config
  notify:
    - "restart logstash shipper"

- name: "install logstash indexer init script"
  action: template src=etc/init.d/logstash-indexer.j2 dest=/etc/init.d/{{ logstash.indexer.service }} owner=root group=root mode=0755
  register: logstash_indexer_init
#  when: with_indexer
  
- name: "install logstash shipper init script"
  action: template src=etc/init.d/logstash-shipper.j2 dest=/etc/init.d/{{ logstash.shipper.service }} owner=root group=root mode=0755
  register: logstash_shipper_init
#  when: with_shipper

- name: chkconfig logstash indexer
  command: chkconfig --add {{ logstash.indexer.service }}
  when: logstash_indexer_init|success
  
- name: chkconfig logstash indexer
  command: chkconfig --add {{ logstash.shipper.service }}
  when: logstash_shipper_init|success

- name: "start logstash indexer"
  action: service name={{ logstash.indexer.service }} state=started
#  when: with_indexer

- name: "start logstash shipper"
  action: service name={{ logstash.shipper.service }} state=started
#  when: with_shipper
