---
elasticsearch_ip_addr: "{{ansible_eth0.ipv4.address}}"
elasticsearch:
  url: http://download.elasticsearch.org/elasticsearch/elasticsearch
  version: "0.90.10"
  tmp: "/tmp"
  service: "elasticsearch"
  bin_dir: /usr/share/elasticsearch/bin
  with_plugins: yes
  plugins:
    - { name: paramedic, origin: karmi/elasticsearch-paramedic }
    - { name: lang-python, origin: elasticsearch/elasticsearch-lang-python/2.0.0.RC1 }
    - { name: transport-memcached, origin: elasticsearch/elasticsearch-transport-memcached/2.0.0.RC1 }
    - { name: transport-thrift, origin: elasticsearch/elasticsearch-transport-thrift/2.0.0.RC1 }
