---
elasticsearch:
  url: http://download.elasticsearch.org/elasticsearch/elasticsearch
  version: "0.90.10"
  tmp: "/tmp"
  service: "elasticsearch"
  bin_dir: /usr/share/elasticsearch/bin
  with_plugins: yes
  plugins:
    - { name: paramedic, origin: karmi/elasticsearch-paramedic }
    - { name: lang-python, origin: elasticsearch/elasticsearch-lang-python/2.0.0.RC1 }

elasticsearch_ip_addr: "{{ansible_eth0.ipv4.address}}"
elasticsearch_logger:
    es:
      logger:
        level: INFO
    rootLogger: INFO, console, file
    logger:
      action: DEBUG
      com.amazonaws: WARN
      index.search.slowlog: TRACE, index_search_slow_log_file
      index.indexing.slowlog: TRACE, index_indexing_slow_log_file
    additivity:
      index.search.slowlog: false
      index.indexing.slowlog: false
    appender:
      console:
        type: console
        layout:
          type: consolePattern
          conversionPattern: "[%d{ISO8601}][%-5p][%-25c] %m%n"
      file:
        type: dailyRollingFile
        file: ${path.logs}/${cluster.name}.log
        datePattern: "'.'yyyy-MM-dd"
        layout:
          type: pattern
          conversionPattern: "[%d{ISO8601}][%-5p][%-25c] %m%n"
      index_search_slow_log_file:
        type: dailyRollingFile
        file: ${path.logs}/${cluster.name}_index_search_slowlog.log
        datePattern: "'.'yyyy-MM-dd"
        layout:
          type: pattern
          conversionPattern: "[%d{ISO8601}][%-5p][%-25c] %m%n"
      index_indexing_slow_log_file:
        type: dailyRollingFile
        file: ${path.logs}/${cluster.name}_index_indexing_slowlog.log
        datePattern: "'.'yyyy-MM-dd"
        layout:
          type: pattern
          conversionPattern: "[%d{ISO8601}][%-5p][%-25c] %m%n"
elasticsearch_config:
  cluster.name: elasticsearch
  path.conf: /etc/elasticsearch
  path.data: /var/lib/elasticsearch
  path.work: /tmp/elasticsearch
  path.logs: /var/log/elasticsearch
  path.plugins: /usr/share/elasticsearch/plugins
