---
# Default Ansible YAML
- name: create conf.d
  file: path={{ item }} state=directory owner=root group=root mode=0644
  sudo: yes
  with_items:
    - /etc/logstash
    - /etc/logstash/conf.d

- name: logstash config build
  template: src=config.j2 dest=/etc/logstash/conf.d/{{ item.config_file }}
  sudo: yes
  with_items: logstash_config 
  
