---
- hosts: elasticsearch
  sudo: yes
  gather_facts: true
  vars_files:
    - "vars/{{ deploy_env }}.yaml"
  roles:
   - role: redis-server
   - role: elasticsearch
   - role: logstash
   - role: kibana
