---
logstash_config:
  redis_server_ip: 127.0.0.1
  elasticsearch_ip: 127.0.0.1
  sincedb_path: /tmp/.logstash_sincedb
logstash:
  version: 1.3.3
  jar: logstash-1.3.3-flatjar.jar
  url: https://download.elasticsearch.org/logstash/logstash
  bin_dir: /usr/share/logstash/bin
  config_path: /etc/logstash
  log_path: /var/log/logstash
  grok_patterns_path: /usr/share/logstash/patterns
  indexer: 
    config: indexer.conf
    log: logstash-indexer.log
    service: 'logstash-indexer'
    name: 'logstash-indexer'
    java_args: ""
  shipper: 
    config: shipper.conf
    log: logstash-shipper.log
    service: 'logstash-shipper'
    name: 'logstash-shipper'
    java_args: ""
  web:
    service: 'logstash-web'
    name: 'logstash-web'
