---
- name: install httpd via yum
  yum: name={{ item }} state=installed
  with_items:
    - httpd

- name: setup json logging
  copy: src=etc/httpd/conf.d/json_log.conf dest=/etc/httpd/conf.d/json_log.conf owner=root
  notify: restart httpd

- name: ensure httpd started
  service: name=httpd state=started
