---

- include: httpd_deb.yaml tags=httpd
  when: ansible_distribution in [ 'Debian', 'Ubuntu' ]

- include: httpd_rpm.yaml tags=httpd
  when: ansible_distribution in [ 'Red Hat Enterprise Linux', 'CentOS', 'Amazon' ]
  

