---
- name: "Fetch Elasticsearch"
  get_url: url={{ elasticsearch.url }}/elasticsearch-{{ elasticsearch.version }}.deb dest={{ elasticsearch.tmp }}
  register: elasticsearch_deb

- name: "Install Elasticsearch package"
  action: shell dpkg -i -E --force-confnew {{ elasticsearch.tmp }}/elasticsearch-{{ elasticsearch.version }}.deb

- name: "Ensure Elasticsearch is running"
  service: name={{ elasticsearch.deb.service }} state=started
