---
- name: set ulimits to unlimited
  shell: ulimit -l unlimited

- include: elasticsearch_deb.yaml tags=elasticsearch
  when: ansible_distribution in [ 'Debian', 'Ubuntu' ]

- include: elasticsearch_rpm.yaml tags=elasticsearch
  when: ansible_distribution in [ 'Red Hat Enterprise Linux', 'CentOS', 'Amazon' ]


#- name: write new es-config
#  action: copy content="{{ item.content }}" dest={{ item.dest }} backup=yes
#  notify: "Restart {{ elasticsearch.service }}"
#  with_items:
#    - { content: "{{ elasticsearch.config|to_nice_yaml }}", dest: /etc/elasticsearch/elasticsearch.yml }
#    - { content: "{{ elasticsearch.logging|to_nice_yaml }}", dest: /etc/elasticsearch/logging.yml }

- name: "Ensure Elasticsearch is running"
  service: name={{ elasticsearch.service }} state=started

- name: include plugin tasks
  include: plugins.yaml
