---
- name: set ulimits to unlimited
  shell: ulimit -l unlimited

- include: elasticsearch_deb.yaml tags=elasticsearch
  when: ansible_distribution in [ 'Debian', 'Ubuntu' ]

- include: elasticsearch_rpm.yaml tags=elasticsearch
  when: ansible_distribution in [ 'Red Hat Enterprise Linux', 'CentOS', 'Amazon' ]


- name: write new es-config
  template: src={{ item }}.j2 dest=/{{ item }}
  notify: "Restart {{ elasticsearch.service }}"
  with_items:
    - etc/elasticsearch/elasticsearch.yml
    - etc/elasticsearch/logging.yml

- name: "Ensure Elasticsearch is running"
  service: name={{ elasticsearch.service }} state=started
