---
- name: set ulimits to unlimited
  shell: ulimit -l unlimited

- include: elasticsearch_deb.yaml tags=elasticsearch
  when: ansible_distribution in [ 'Debian', 'Ubuntu' ]

- include: elasticsearch_rpm.yaml tags=elasticsearch
  when: ansible_distribution in [ 'Red Hat Enterprise Linux', 'CentOS', 'Amazon' ]


- name: write new es-config
  template: src=etc/elasticsearch/elasticsearch.yml.j2 dest={{ elasticsearch_config['path.conf'] }}/elasticsearch.yml 
  notify: "Restart {{ elasticsearch.service }}"

- name: write new es-logger-config
  copy: content="{{ item.content }}" dest={{ item.dest }}
  notify: "Restart {{ elasticsearch.service }}"
  with_items:
    - { content: "{{ elasticsearch_logger|to_nice_yaml }}", dest: "{{ elasticsearch_config['path.conf'] }}/logging.yml" }

- name: "Ensure Elasticsearch is running"
  service: name={{ elasticsearch.service }} state=started

- name: include plugin tasks
  include: plugins.yaml
