---
logstash:
  url: http://download.elasticsearch.org/logstash/logstash/packages/
  version: "1.3.3-1"
  tmp: "/tmp"
  service: "logstash"
  start: true
  open_files: 16384
#  java_opts: "-Xmx256m -Djava.io.tmpdir=$LS_HOME/tmp"
logstash_config: []
